name: 'Regrada - AI Regression Tests'
description: 'Detect behavioral regressions in LLM-powered apps before they hit production'
author: 'Regrada'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  tests:
    description: 'Path to test suite file'
    required: false
    default: 'evals/tests.yaml'
  baseline:
    description: 'Path to baseline file'
    required: false
    default: '.regrada/baseline.json'
  fail-on-regression:
    description: 'Fail the workflow if regressions are detected'
    required: false
    default: 'true'
  fail-on-failure:
    description: 'Fail the workflow if any test fails (not just regressions)'
    required: false
    default: 'false'
  comment-on-pr:
    description: 'Post results as a PR comment'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for running tests'
    required: false
    default: '.'

outputs:
  total:
    description: 'Total number of tests'
    value: ${{ steps.run.outputs.total }}
  passed:
    description: 'Number of passed tests'
    value: ${{ steps.run.outputs.passed }}
  failed:
    description: 'Number of failed tests'
    value: ${{ steps.run.outputs.failed }}
  regressions:
    description: 'Number of regressions (tests that were passing but now fail)'
    value: ${{ steps.run.outputs.regressions }}
  result:
    description: 'Overall result: success, failure, or regression'
    value: ${{ steps.run.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Build Regrada
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o regrada .
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Run Evaluations
      id: run
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e

        regrada run \
          --ci \
          --tests "${{ inputs.tests }}" \
          --baseline "${{ inputs.baseline }}" \
          --output json > .regrada/results.json 2>&1

        EXIT_CODE=$?

        # Parse results
        if [ -f .regrada/results.json ]; then
          TOTAL=$(jq -r '.total_tests // 0' .regrada/results.json)
          PASSED=$(jq -r '.passed // 0' .regrada/results.json)
          FAILED=$(jq -r '.failed // 0' .regrada/results.json)
          REGRESSIONS=$(jq -r '.regressions // 0' .regrada/results.json)
        else
          TOTAL=0
          PASSED=0
          FAILED=0
          REGRESSIONS=0
        fi

        echo "total=$TOTAL" >> $GITHUB_OUTPUT
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "failed=$FAILED" >> $GITHUB_OUTPUT
        echo "regressions=$REGRESSIONS" >> $GITHUB_OUTPUT

        # Determine result
        if [ "$REGRESSIONS" -gt 0 ]; then
          echo "result=regression" >> $GITHUB_OUTPUT
        elif [ "$FAILED" -gt 0 ]; then
          echo "result=failure" >> $GITHUB_OUTPUT
        else
          echo "result=success" >> $GITHUB_OUTPUT
        fi

        # Print summary to logs
        echo "## Regrada Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Total | $TOTAL |" >> $GITHUB_STEP_SUMMARY
        echo "| Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
        echo "| Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
        echo "| Regressions | $REGRESSIONS |" >> $GITHUB_STEP_SUMMARY

        # Determine exit code based on inputs
        if [ "${{ inputs.fail-on-regression }}" = "true" ] && [ "$REGRESSIONS" -gt 0 ]; then
          echo "exit_code=1" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.fail-on-failure }}" = "true" ] && [ "$FAILED" -gt 0 ]; then
          echo "exit_code=1" >> $GITHUB_OUTPUT
        else
          echo "exit_code=0" >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const workdir = '${{ inputs.working-directory }}';
          const resultsPath = workdir === '.' ? '.regrada/results.json' : `${workdir}/.regrada/results.json`;

          let result;
          try {
            result = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
          } catch (e) {
            console.log('Could not read results:', e.message);
            return;
          }

          let status = 'âœ…';
          if (result.regressions > 0) status = 'ðŸ”´';
          else if (result.failed > 0) status = 'âš ï¸';

          let body = `## ${status} Regrada AI Test Results\n\n`;
          body += `| Tests | Passed | Failed | Regressions |\n`;
          body += `|:-----:|:------:|:------:|:-----------:|\n`;
          body += `| ${result.total_tests} | ${result.passed} | ${result.failed} | ${result.regressions} |\n\n`;

          if (result.regressions > 0 && result.comparison?.new_failures) {
            body += `### ðŸ”´ Regressions Detected\n\n`;
            body += `These tests were **passing** in the baseline but are now **failing**:\n\n`;
            result.comparison.new_failures.forEach(name => {
              body += `- \`${name}\`\n`;
            });
            body += `\n`;
          }

          if (result.failed > 0) {
            body += `<details><summary>View Failed Tests</summary>\n\n`;
            result.test_results
              .filter(t => t.status === 'failed')
              .forEach(t => {
                body += `#### \`${t.name}\`\n`;
                t.checks
                  .filter(c => !c.passed)
                  .forEach(c => {
                    body += `- **${c.check}**: ${c.message || 'Failed'}\n`;
                  });
                body += `\n`;
              });
            body += `</details>\n\n`;
          }

          if (result.comparison?.new_passes?.length > 0) {
            body += `### âœ… Improvements\n\n`;
            body += `These tests were failing but are now passing:\n\n`;
            result.comparison.new_passes.forEach(name => {
              body += `- \`${name}\`\n`;
            });
            body += `\n`;
          }

          body += `---\n`;
          body += `*[Regrada](https://github.com/matiasmolinolo/regrada) - CI for AI*`;

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const existing = comments.find(c =>
            c.user.type === 'Bot' && c.body.includes('Regrada AI Test Results')
          );

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }

    - name: Check Result
      if: steps.run.outputs.exit_code == '1'
      shell: bash
      run: |
        echo "::error::Regrada detected regressions or failures"
        exit 1
